### PR TITLE
refresh deps, add maintainer

### LINKED ISSUE #59: Dependencies have drifted from upstream?
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

A quick look at `meta.yaml` vs `setup.py` upstream indicates that some drift has occurred: 
- `packaging` is missing
- several version pins have shifted
- some dependencies appear to have been removed, or made platform specific

### Proposal

- sync with upstream (a la `grayskull`)
- add `pip check`

### Installed packages

```shell
jupyterhub 2.2.2
```

### Environment info

```shell
jupyterhub 2.2.2
```

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Notes:
- fixes #59
- refreshes deps
- updates some metadata
- add self as maintainer

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge/jupyterhub ready for review

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by minrk** [comment]
Thanks!

**Pull request merged**
