### PR TITLE
jupyterhub 0.8.0

### PR DESCRIPTION
**Pull request by minrk**

### CODE REVIEW

**Comment by jakirkham** [comment]
Would it be possible to include the license file as well?

**Comment by minrk** [comment]
@jakirkham done

**Comment by jakirkham** [comment]
Thanks. 😄

**Comment by mariusvniekerk** [comment]
We can probably also build this as a python no-arch conda package?

**Comment by minrk** [comment]
@mariusvniekerk I tried that earlier today, but alas no. I was just about to open an issue about that on conda-build. `noarch: python` packages cannot handle data_files for some reason, and JupyterHub uses data_files to deliver some resources to $PREFIX/share.

conda-build issue: https://github.com/conda/conda-build/issues/2419

**Comment by minrk** [comment]
#11 demonstrates why `noarch: python` doesn't work and conda/conda-build#2420 fixes the problem in conda-build.

**Pull request merged**
