### PR TITLE
Use node 12 and add myself and consideRatio

### LINKED ISSUE #33: Recipe depends on older node
Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /Users/stslve/miniconda/envs/jhub-test:
#
# Name                    Version                   Build  Channel
alembic                   1.4.2              pyh9f0ad1d_0    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     19.3.0                     py_0    conda-forge
blinker                   1.4                        py_1    conda-forge
brotlipy                  0.7.0           py38h64e0658_1000    conda-forge
c-ares                    1.16.1               haf1e3a3_0    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py38h32f6830_0    conda-forge
certipy                   0.1.3                      py_0    conda-forge
cffi                      1.14.1           py38hc4dd44e_0    conda-forge
chardet                   3.0.4           py38h32f6830_1006    conda-forge
configurable-http-proxy   4.2.1           node10_h1f298a6_0    conda-forge
cryptography              3.0              py38h52adbb4_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
entrypoints               0.3             py38h32f6830_1001    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
importlib-metadata        1.7.0            py38h32f6830_0    conda-forge
importlib_metadata        1.7.0                         0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jsonschema                3.2.0            py38h32f6830_1    conda-forge
jupyter_telemetry         0.0.5                      py_0    conda-forge
jupyterhub                1.1.0            py38h32f6830_3    conda-forge
jupyterhub-base           1.1.0            py38h32f6830_3    conda-forge
krb5                      1.17.1               h14dd6a4_2    conda-forge
libcurl                   7.71.1               he6690cf_4    conda-forge
libcxx                    10.0.1               h5f48129_0    conda-forge
libedit                   3.1.20191231         hed1e85f_1    conda-forge
libev                     4.33                 haf1e3a3_0    conda-forge
libffi                    3.2.1             h4a8c4bd_1007    conda-forge
libnghttp2                1.41.0               h8a08a2b_1    conda-forge
libssh2                   1.9.0                h39bdce6_5    conda-forge
mako                      1.1.3              pyh9f0ad1d_0    conda-forge
markupsafe                1.1.1            py38h64e0658_1    conda-forge
ncurses                   6.2                  hb1e8313_1    conda-forge
nodejs                    10.13.0              h0a44026_0
oauthlib                  3.0.1                      py_0    conda-forge
openssl                   1.1.1g               h0b31af3_1    conda-forge
pamela                    1.0.0                      py_0    conda-forge
pip                       20.2.1                     py_0    conda-forge
prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pycurl                    7.43.0.5         py38h1c2e396_2    conda-forge
pyjwt                     1.7.1                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyrsistent                0.16.0           py38h64e0658_0    conda-forge
pysocks                   1.7.1            py38h32f6830_1    conda-forge
python                    3.8.5           h85f3143_2_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-editor             1.0.4                      py_0    conda-forge
python-json-logger        0.1.11                     py_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
readline                  8.0                  h0678c8f_2    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
ruamel.yaml               0.16.6           py38h64e0658_1    conda-forge
ruamel.yaml.clib          0.2.0            py38h64e0658_1    conda-forge
setuptools                49.3.0           py38h32f6830_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlalchemy                1.3.18           py38h64e0658_0    conda-forge
sqlite                    3.32.3               h93121df_1    conda-forge
tk                        8.6.10               hbbe82c9_0    conda-forge
tornado                   6.0.4            py38h64e0658_1    conda-forge
traitlets                 4.3.3            py38h32f6830_1    conda-forge
urllib3                   1.25.10                    py_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xz                        5.2.5                h0b31af3_1    conda-forge
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11                     1007    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : jhub-test
    active env location : /Users/stslve/miniconda/envs/jhub-test
            shell level : 2
       user config file : /Users/stslve/.condarc
 populated config files : /Users/stslve/.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.7.4.final.0
       virtual packages : __osx=10.14.6
       base environment : /Users/stslve/miniconda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/stslve/miniconda/pkgs
                          /Users/stslve/.conda/pkgs
       envs directories : /Users/stslve/miniconda/envs
                          /Users/stslve/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.3 requests/2.24.0 CPython/3.7.4 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 1919889055:1896053708
             netrc file : /Users/stslve/.netrc
           offline mode : False
```
</details>

The version of `nodejs` that comes in is not compatible with JupyterLab:

```
configurable-http-proxy   4.2.1           node10_h1f298a6_0    conda-forge
nodejs                    10.13.0              h0a44026_0
```

`error jest-worker@26.0.0: The engine "node" is incompatible with this module. Expected version ">= 10.14.2". Got "10.13.0"`

Is there a way to specify in this recipe to use the `node12` version of `configurable-http-proxy`?

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #33 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by blink1073** [comment]
@conda-forge-admin, please rerender

**Comment by blink1073** [comment]
Requirement appears to be working:

`2020-08-12T11:01:44.5604419Z     configurable-http-proxy: 4.2.1-node12_hbce0df8_0  conda-forge`

**Comment by blink1073** [comment]
@consideRatio are you okay with me adding you as a maintainer here?

**Comment by consideRatio** [comment]
@blink1073 absolutely!

**Comment by blink1073** [comment]
With the `nodejs` requirement instead:

`2020-08-12T11:17:47.0110039Z     nodejs:                  14.7.0-h568c755_0         conda-forge`

**Comment by blink1073** [comment]
Thanks for the assist @ocefpaf!

**Comment by ocefpaf** [comment]
Thank you for taking care of this package!

**Pull request merged**
