### PR TITLE
Pin minimal jupyter_telemetry

### PR DESCRIPTION
**Pull request by fcollonval**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This add `pip check` validation test. And therefore it also correct the minimal version needed for jupyter_telemetry.

### CODE REVIEW

**Comment by fcollonval** [comment]
@conda-forge-admin, please rerender

**Review by consideRatio — APPROVED** [review]
LGTM :+1:

**Comment by fcollonval** [comment]
> LGTM +1

Thanks for the quick feedback @consideRatio 
This will probably requires https://github.com/conda-forge/jupyter_telemetry-feedstock/pull/4 to be merged to work. I realized that the latest 0.1.0 version of `jupyter_telemetry` was not published on conda-forge due to an error on `anaconda upload`: https://github.com/conda-forge/jupyter_telemetry-feedstock/runs/1096039648

**Comment by minrk** [comment]
closed & reopened to poke CI

**Review by minrk — APPROVED** [review]

**Comment by fcollonval** [comment]
jupyter_telemetry 0.1.0 is now listed on conda-forge. So closing/reopening to trigger the CI.

**Comment by fcollonval** [comment]
Remaining error:
```
(%PREFIX%) %SRC_DIR%>pip check 
jupyterhub 1.2.1 requires pamela, which is not installed.
```

**Comment by minrk** [comment]
merged as part of #39

**Pull request closed without merging**
